/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "LOGROCKET_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Post": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SeedDatabase": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Tag": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}